### ISSUE TITLE
Predicting the emotion using saved DL model - Error: str attribute has no object ndim

### ISSUE THREAD

**Issue by Nandy-Saran** [harry-7/speech-emotion-recognition#13]
The python file dl_example ran correctly and we got an accuracy of 0.98 with the training set. We then tried to predict the emotion using `predict()` function by giving a wave file as an argument. We preloaded the model `best_model_LSTM.h5` from the models' folder.

Here is the screenshot of the code of the file dl_example.py
![dl (1)](https://user-images.githubusercontent.com/32573768/55057918-9c577200-5090-11e9-98f3-297c7ee22a38.PNG)

The error and stack trace is attached.
![o1](https://user-images.githubusercontent.com/32573768/55057638-c52b3780-508f-11e9-8ed9-c14964d05be1.PNG)
![o2](https://user-images.githubusercontent.com/32573768/55057643-c78d9180-508f-11e9-9be0-f45e71b72c26.PNG)
![o3](https://user-images.githubusercontent.com/32573768/55057648-c9575500-508f-11e9-9ea8-18ff3b837dcf.PNG)

Please look into the issue as soon as you can Harry. Thanks again :)

**Comment by hkveeranki** [comment]
So, the predict method takes 2D numpy array of size NxM. Where N is number of samples you want to predict and M is the feature vector for each of the samples. So in this case you would need to extract the feature vector and pass them instead of the filename of the wav file. Then you should be able to predict its label. This reminds me that there is no direct method available in utilities to do this. I will try to add methods necessary to do this.

**Comment by hkveeranki** [comment]
If you are able to run the ML example, can you please close the other issue I opened?

**Comment by hkveeranki** [comment]
@Nandy-Saran  FYI, I updated the package. It is now possible to predict label for a single sample. I also updated examples to show how it is done. Take a look and re open this issue if you need anything else.
